/**
 * The app manifest — one JSON file describing the app's API surface:
 * every contract (method, path, auth, tenant scope, input and output types),
 * every feature and how it decides auth, and the Prisma models that carry a
 * tenant column.
 *
 * `bloom manifest` writes it to bloom.manifest.json and refreshes the
 * generated section of the app's AGENTS.md (and llms.txt, if the app has
 * one), so an agent reads the API from one place instead of the codebase.
 * `bloom check` fails when either is out of date.
 *
 * The output is deterministic — sorted, no timestamps, no versions — so it
 * only changes when the API does, and a diff of it is a diff of the API.
 */
import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import type { ManifestContract } from './load.js';

export type { ManifestContract } from './load.js';

export interface ManifestFeature {
  name: string;
  /** Route file, relative to the app. */
  file: string;
  /** 'contracts' when it serves route(contract, …); otherwise a plain Express router. */
  kind: 'contracts' | 'router';
  /** Plain routers only: how the file decides auth. */
  auth?: 'guarded' | 'public' | 'none';
}

export interface Manifest {
  manifest: 1;
  contracts: ManifestContract[];
  features: ManifestFeature[];
  /** Prisma models with a tenant column (tenantId / tenant_id). */
  tenantModels: string[];
}

export const MANIFEST_FILE = 'bloom.manifest.json';
const START = '<!-- bloom:manifest:start — generated by `bloom manifest`; edits here are overwritten -->';
const END = '<!-- bloom:manifest:end -->';

export class ManifestError extends Error {
  constructor(message: string, readonly fix: string) {
    super(message);
    this.name = 'ManifestError';
  }
}

function walk(dir: string, match: (file: string) => boolean, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, match, out);
    else if (match(full)) out.push(full);
  }
  return out;
}

const GUARD = /\b(?:auth\s*\.\s*)?require(?:LoginToken|UserRoles|ApiToken|Roles|LoginOrApiToken|Tier|Scope)\s*\(/;
const PUBLIC = /export\s+const\s+isPublic\s*=\s*true/;

function readFeatures(root: string): ManifestFeature[] {
  const dir = join(root, 'src', 'api', 'features');
  if (!existsSync(dir)) return [];
  const out: ManifestFeature[] = [];
  for (const name of readdirSync(dir).sort()) {
    const featureDir = join(dir, name);
    if (!statSync(featureDir).isDirectory() || name.startsWith('_') || name.startsWith('.')) continue;
    const main = [`${name}.route.ts`, `${name}.route.js`].find((f) => existsSync(join(featureDir, f)));
    if (!main) continue;
    const src = readFileSync(join(featureDir, main), 'utf8');
    const file = relative(root, join(featureDir, main));
    if (/\bcontractRouter\s*\(/.test(src)) out.push({ name, file, kind: 'contracts' });
    else out.push({ name, file, kind: 'router', auth: GUARD.test(src) ? 'guarded' : PUBLIC.test(src) ? 'public' : 'none' });
  }
  return out;
}

function readTenantModels(root: string): string[] {
  const schemas = walk(root, (f) => f.endsWith('.prisma'));
  const models: string[] = [];
  for (const file of schemas) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(/^\s*model\s+(\w+)\s*\{([\s\S]*?)^\s*\}/gm)) {
      if (/^\s*(tenantId|tenant_id)\s/m.test(m[2])) models.push(m[1]);
    }
  }
  return [...new Set(models)].sort();
}

/** Load the app's contract files with the app's own tsx. */
function readContracts(root: string): ManifestContract[] {
  const files = walk(join(root, 'src'), (f) => /\.contract\.[jt]s$/.test(f) && !f.endsWith('.d.ts'));
  if (files.length === 0) return [];
  try {
    createRequire(join(root, 'package.json')).resolve('tsx');
  } catch {
    throw new ManifestError(
      'The manifest loads contract files with tsx, and tsx is not installed in this app.',
      'npm install -D tsx (every Bloom starter has it), then run bloom manifest again.',
    );
  }
  const loader = join(dirname(fileURLToPath(import.meta.url)), 'load.js');
  const run = spawnSync(process.execPath, ['--import', 'tsx', loader, ...files], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  if (run.status !== 0) {
    throw new ManifestError(
      `Loading the contract files failed: ${(run.stderr || run.error?.message || '').trim().split('\n')[0]}`,
      'Run `npx tsx <file>.contract.ts` to see the full error.',
    );
  }
  const result = JSON.parse(run.stdout) as { contracts: ManifestContract[]; failed: Array<{ file: string; error: string }> };
  if (result.failed.length) {
    const f = result.failed[0];
    throw new ManifestError(
      `${f.file} failed to load: ${f.error}`,
      'Contract files may import only zod and @bloomneo/bloom (they are compiled by both builds).',
    );
  }
  return result.contracts.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

export function buildManifest(root: string): Manifest {
  return {
    manifest: 1,
    contracts: readContracts(root),
    features: readFeatures(root),
    tenantModels: readTenantModels(root),
  };
}

export function serializeManifest(m: Manifest): string {
  return JSON.stringify(m, null, 2) + '\n';
}

function authLabel(auth: unknown): string {
  if (typeof auth === 'string') return auth;
  const roles = (auth as { roles?: string[] })?.roles;
  return roles ? `roles: ${roles.join(', ')}` : JSON.stringify(auth);
}

/** The generated Markdown section: the API an agent should know about. */
export function renderSection(m: Manifest): string {
  const lines = [START, '', '## This app\'s API (generated)', ''];
  lines.push(`Source of truth: \`${MANIFEST_FILE}\`. Regenerate with \`npx bloom manifest\`; \`bloom check\` fails when it is stale.`, '');
  if (m.contracts.length) {
    lines.push('| Route | Auth | Tenant | Input | Response | Contract |', '|---|---|---|---|---|---|');
    for (const c of m.contracts) {
      const input = (['params', 'query', 'body'] as const)
        .filter((p) => c[p])
        .map((p) => `${p} \`${c[p]}\``)
        .join('<br>');
      const esc = (s: string) => s.replace(/\|/g, '\\|');
      lines.push(
        `| \`${c.method} ${c.path}\`${c.summary ? `<br>${esc(c.summary)}` : ''} | ${authLabel(c.auth)} | ${c.tenant ? 'yes' : 'no'} | ${esc(input) || '—'} | ${c.response ? `\`${esc(c.response)}\`` : '—'} | \`${c.name}\` in ${c.file} |`,
      );
    }
    lines.push('');
  }
  const legacy = m.features.filter((f) => f.kind === 'router');
  if (legacy.length) {
    lines.push('Plain Express routers (no contract yet): ' + legacy.map((f) => `\`/api/${f.name}\` (${f.auth})`).join(', ') + '.', '');
  }
  if (m.tenantModels.length) {
    lines.push(`Tenant-scoped models: ${m.tenantModels.map((x) => `\`${x}\``).join(', ')}.`, '');
  }
  lines.push(END);
  return lines.join('\n');
}

/** `text` with the generated section replaced (or appended). */
export function withSection(text: string, section: string): string {
  const s = text.indexOf(START);
  const e = text.indexOf(END);
  if (s !== -1 && e > s) return text.slice(0, s) + section + text.slice(e + END.length);
  return text.replace(/\s*$/, '\n\n') + section + '\n';
}

export interface ManifestFiles {
  /** Path (relative to the app) → content it should have. */
  expected: Record<string, string>;
  /** Paths whose content differs from what is on disk. */
  stale: string[];
}

/** What bloom manifest would write, and which of those files are out of date. */
export function manifestFiles(root: string, manifest: Manifest = buildManifest(root)): ManifestFiles {
  const expected: Record<string, string> = { [MANIFEST_FILE]: serializeManifest(manifest) };
  const section = renderSection(manifest);
  for (const doc of ['AGENTS.md', 'llms.txt']) {
    const path = join(root, doc);
    // AGENTS.md always gets the section; llms.txt only if the app has one.
    if (!existsSync(path) && doc !== 'AGENTS.md') continue;
    expected[doc] = withSection(existsSync(path) ? readFileSync(path, 'utf8') : '# AGENTS.md\n', section);
  }
  const stale = Object.entries(expected)
    .filter(([p, content]) => !existsSync(join(root, p)) || readFileSync(join(root, p), 'utf8') !== content)
    .map(([p]) => p);
  return { expected, stale };
}

export function writeManifest(root: string): ManifestFiles {
  const files = manifestFiles(root);
  for (const p of files.stale) writeFileSync(join(root, p), files.expected[p]);
  return files;
}
