# AGENTS.md — {{PROJECT_NAME}}

> Project-level agent rules. For full API references, read the files in `docs/`
> (auto-generated by postinstall from the installed package versions).

## What this project is

A desktop FBCA app generated by `@bloomneo/bloom`. Electron app with:

- **Frontend (renderer)**: React + `@bloomneo/uikit`
- **Backend (main process)**: Express + `@bloomneo/appkit`

## Where to find the API docs

After `npm install`:

| File | Contents |
|------|----------|
| `docs/appkit.md` | Full `@bloomneo/appkit` API reference |
| `docs/appkit-agents.md` | AppKit agent rules |
| `docs/uikit.md` | Full `@bloomneo/uikit` API reference |

## Project structure

```
src/
├── desktop/main/features/  # Electron main process (AppKit)
└── web/features/           # Renderer (UIKit, auto-routed pages)
electron/                   # Electron entry point
```

## Key conventions

- `xxxClass.get()` — always, never `new SomethingClass()`
- `error.asyncRoute()` wraps async route handlers
- `<ThemeProvider>` required around all UIKit components
- `DATABASE_URL=file:./app.db` for local SQLite

See `docs/appkit.md` + `docs/uikit.md` for full API.
