/**
 * User seed — three role tiers matching ADMIN_USER_ROLES defaults.
 * @file prisma/seeding/user.seed.js
 *
 * Creates one account per role:
 *   admin@example.com       (admin.system)
 *   moderator@example.com   (moderator.manage)
 *   user@example.com        (user.basic)
 *
 * DEFAULT_USER_PASSWORD env var must be set (generated by bloom at
 * scaffold time). No hardcoded passwords in the repo.
 *
 * Idempotent: if the User table already has rows, seeding is skipped.
 *
 * Run directly: `node prisma/seeding/user.seed.js`
 * Or via:       `npm run db:seed`
 */

import dotenv from 'dotenv';
import { databaseClass } from '@bloomneo/appkit/database';
import { authClass } from '@bloomneo/appkit/auth';

dotenv.config();

export async function seedUsers() {
  console.log('🌱 Seeding user accounts…');

  const db = await databaseClass.get();
  const auth = authClass.get();

  const existingCount = await db.user.count();
  if (existingCount > 0) {
    console.log(`⚠️  User table has ${existingCount} rows. Skipping seed.`);
    return { skipped: true, count: existingCount };
  }

  const defaultPassword = process.env.DEFAULT_USER_PASSWORD;
  if (!defaultPassword) {
    throw new Error('DEFAULT_USER_PASSWORD env var is required for seeding');
  }
  const hashed = await auth.hashPassword(defaultPassword);

  const users = [
    {
      email: 'admin@example.com',
      password: hashed,
      name: 'Admin',
      phone: '+1-555-0100',
      role: 'admin',
      level: 'system',
      isVerified: true,
      isActive: true,
    },
    {
      email: 'moderator@example.com',
      password: hashed,
      name: 'Moderator',
      phone: '+1-555-0200',
      role: 'moderator',
      level: 'manage',
      isVerified: true,
      isActive: true,
    },
    {
      email: 'user@example.com',
      password: hashed,
      name: 'Regular User',
      phone: '+1-555-0300',
      role: 'user',
      level: 'basic',
      isVerified: true,
      isActive: true,
    },
  ];

  const result = await db.user.createMany({ data: users });

  console.log(`✅ Created ${result.count} user accounts.`);
  console.log(`   Default password: ${defaultPassword}`);
  console.log(`
  🔑 admin@example.com       (admin.system)
  🛡️  moderator@example.com   (moderator.manage)
  👤 user@example.com         (user.basic)
`);

  return { seeded: true, count: result.count };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  seedUsers()
    .then((r) => console.log('User seeding completed:', r))
    .catch((err) => {
      console.error('User seeding failed:', err);
      process.exit(1);
    });
}
