# AGENTS.md — {{PROJECT_NAME}}

> Project-level agent rules. For full API references, read the files in `docs/`
> (auto-generated by postinstall from the installed package versions).

## What this project is

A mobile FBCA app generated by `@bloomneo/bloom`. React + Capacitor targeting
iOS and Android, using `@bloomneo/uikit` for components. Connects to an
external API (not bundled — deploy your appkit backend separately).

## Where to find the API docs

After `npm install`:

| File | Contents |
|------|----------|
| `docs/uikit.md` | Full `@bloomneo/uikit` API — components, hooks, layouts, mobile patterns |

## Project structure

```
src/
└── web/
    ├── features/           # One folder per feature
    │   └── {feature}/
    │       ├── pages/      # Auto-discovered routes (file → URL)
    │       ├── components/ # Feature-specific components
    │       └── hooks/      # Feature-specific hooks
    ├── shared/             # Reused across features
    └── App.tsx
```

## Key conventions

- Wrap app in `<ThemeProvider>` — required for all UIKit components
- Wrap app in `<ToastProvider>` — required for `useToast()`
- Use `MobileLayout` / `SafeArea` / `TabBar` from UIKit for mobile chrome
- API calls go to your external backend via `fetch` or `axios`
- Auto-routing: files in `features/*/pages/` become routes automatically

## Mobile development

```bash
npm run dev                    # browser preview
npm run mobile:run:android     # Android emulator
npm run mobile:run:ios         # iOS simulator (Mac only)
```

See `docs/uikit.md` for full component API.
